In [2]:
import numpy as np
import pandas as pd

### NumPy Array

In [3]:
A = [1,2,3]

In [4]:
B = np.array(A)

In [5]:
B

array([1, 2, 3])

In [6]:
A

[1, 2, 3]

In [7]:
C = np.array([[7,8,9],[4,5,6]])
C

array([[7, 8, 9],
       [4, 5, 6]])

In [8]:
C = np.array([[7,8,9],[4,5,6], [10,11,12]])
C

array([[ 7,  8,  9],
       [ 4,  5,  6],
       [10, 11, 12]])

In [9]:
D = [[7,8,9],[4,5,6], [10,11,12]]
D

[[7, 8, 9], [4, 5, 6], [10, 11, 12]]

### Pandas DataFrame

In [11]:
x = np.linspace(1,10,10)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
y = x * x

In [13]:
z = np.sqrt(x)

In [14]:
df = pd.DataFrame({'x':x, 'y':y, 'z':z})

In [15]:
print(df)

      x      y         z
0   1.0    1.0  1.000000
1   2.0    4.0  1.414214
2   3.0    9.0  1.732051
3   4.0   16.0  2.000000
4   5.0   25.0  2.236068
5   6.0   36.0  2.449490
6   7.0   49.0  2.645751
7   8.0   64.0  2.828427
8   9.0   81.0  3.000000
9  10.0  100.0  3.162278


In [16]:
df

x      y         z
0   1.0    1.0  1.000000
1   2.0    4.0  1.414214
2   3.0    9.0  1.732051
3   4.0   16.0  2.000000
4   5.0   25.0  2.236068
5   6.0   36.0  2.449490
6   7.0   49.0  2.645751
7   8.0   64.0  2.828427
8   9.0   81.0  3.000000
9  10.0  100.0  3.162278